# golangci-lint configuration
# See https://golangci-lint.run/usage/configuration/

version: 2

run:
  timeout: 5m
  tests: true

issues:
  exclude-dirs:
    - vendor
  exclude-files:
    - ".*\\.pb\\.go$"
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - misspell
    - gocritic
    - revive

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false  # Allow blank identifier for intentionally ignored errors
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  revive:
    rules:
      - name: exported
        disabled: true  # Too many false positives
      - name: var-naming
        severity: warning
      - name: package-comments
        disabled: true  # Optional documentation

  # Allow ignoring errors in specific cases
  exclude-rules:
    # Allow ignoring errors in benchmarks and tests
    - path: _test\.go
      linters:
        - errcheck
    # Allow ignoring errors in HTTP handlers (write errors are often non-critical)
    - path: pkg/server/http\.go
      linters:
        - errcheck
    # Allow ignoring errors in cleanup code
    - path: pkg/tunnel/manager\.go
      text: "Process.Kill"
      linters:
        - errcheck
    # Allow ignoring errors in detector cleanup
    - path: pkg/detector/service\.go
      text: "Body.Close"
      linters:
        - errcheck

